name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: node --version
    - uses: borales/actions-yarn@v4
      with:
        cmd: install
    #- uses: borales/actions-yarn@v2.0.0
    #  with:
    #      cmd: build
    - uses: borales/actions-yarn@v4
      with:
          cmd: lint
    - uses: borales/actions-yarn@v4
      with:
          cmd: format-check
    - uses: borales/actions-yarn@v4
      with:
          cmd: test
